require: rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRailsVersion: 4.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Gemfile
    - 'hooks/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Layout/LineLength:
  Max: 122

Style/SingleLineBlockParams:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

# TODO - fix app/
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'app/models/repositories/released_ticket_repository.rb'
    - 'app/models/commit_status.rb'
    - 'app/models/git_repository.rb'
    - 'app/models/git_repository_loader.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'lib/tasks/**/*'
    - 'config/environments/**/*'

Metrics/AbcSize:
  Max: 20

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/NestedParenthesizedCalls:
  Enabled: false  # TODO: Enable when possible to configure for method arity.

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MultilineBlockChain:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
  Exclude:
    - 'app/use_cases/link_ticket.rb'
    - 'app/use_cases/unlink_ticket.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $healthcheck

Style/HashSyntax:
  Exclude:
    - 'lib/tasks/*'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

# TODO - fix app/decorators
Metrics/ParameterLists:
  Exclude:
    - 'app/mailers/**/*'
    - 'app/decorators/feature_review_with_statuses.rb'
    - 'spec/support/git_test_repository.rb'

# Complains for `_` or `at:`
Naming/MethodParameterName:
  Enabled: false
