# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13989cf79e32813701dcdfdda1315800a89f998ddef025fd8d517b0ae276e5e30ae2c66202dd1c0b2da430aa4ad71f4359224036d5d8e8cf549c065f76d2b6e1

test:
  secret_key_base: e4ee2b70d8f8cfa8d049427d3fdd102dc39c80ddebc5063d4d413920f46cbd49ea30334a62b0e294d5aaa0fb57c6ce6317d489007c9c2a69085c459bb8f4e97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
